openapi: 3.0.1
info:
  title: ReposiTori
  version: 1.0.0
servers:
  - url: https://*/prod/
paths:
  /token:
    get:
      summary: GitHubの認可コードをアクセストークンに交換
      parameters:
        - in: query
          name: code
          schema:
            type: string
          required: true
          description: GitHubの認可コード
      responses:
        "200":
          description: アクセストークンの取得に成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "400":
          description: リクエストが無効
        "500":
          description: サーバーエラー
  /home:
    get:
      summary: 認証されたユーザーのDASHデータを取得
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: "アクセストークン（例: Bearer {token}）"
      responses:
        "200":
          description: DASHデータの取得に成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HomeResponse"
        "401":
          description: 認証エラー
        "500":
          description: サーバーエラー
  /profile:
    post:
      summary: DASHのプロフィールを変更
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: "アクセストークン（例: Bearer {token}）"
      requestBody:
        description: DASHのプロフィール変更リクエスト
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProfileRequest"
      responses:
        "200":
          description: プロフィールの変更に成功
        "401":
          description: 認証エラー
        "500":
          description: サーバーエラー
  /get_feed:
    post:
      summary: 餌を取得
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: "アクセストークン（例: Bearer {token}）"
      requestBody:
        description: 餌取得リクエスト
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetFeedRequest"
      responses:
        "200":
          description: 餌の取得に成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetFeedResponse"
        "400":
          description: 餌の取得が許可されていない
        "401":
          description: 認証エラー
        "500":
          description: サーバーエラー
  /feed:
    post:
      summary: 餌をあげて経験値を増やす
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: "アクセストークン（例: Bearer {token}）"
      requestBody:
        description: 餌やりリクエスト
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FeedRequest"
      responses:
        "200":
          description: 餌やりに成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeedResponse"
        "400":
          description: 餌やりが許可されていない
        "401":
          description: 認証エラー
        "500":
          description: サーバーエラー
  /ranking:
    get:
      summary: キャラクターのランキングを取得
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: "アクセストークン（例: Bearer {token}）"
      responses:
        "200":
          description: ランキングの取得に成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RankingResponse"
        "401":
          description: 認証エラー
        "500":
          description: サーバーエラー
  /clothes:
    post:
      summary: 服装を変更
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: "アクセストークン（例: Bearer {token}）"
      requestBody:
        description: 服装変更のリクエスト
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClothesRequest"
      responses:
        "200":
          description: 服装の変更に成功
        "400":
          description: リクエストが無効
        "401":
          description: 認証エラー
        "500":
          description: サーバーエラー
  /background:
    post:
      summary: 背景を変更
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: "アクセストークン（例: Bearer {token}）"
        - in: query
          name: item
          schema:
            type: string
          required: true
          description: 変更する背景
      requestBody:
        description: 服装変更のリクエスト
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BackgroundRequest"
      responses:
        "200":
          description: 背景の変更に成功
        "400":
          description: リクエストが無効
        "401":
          description: 認証エラー
        "500":
          description: サーバーエラー
components:
  schemas:
    TokenResponse:
      type: object
      properties:
        access_token:
          type: string
          description: 認証されたリクエストに使用するアクセストークン
    HomeResponse:
      type: object
      properties:
        userId:
          type: string
          description: ユーザーの一意の識別子
        userName:
          type: string
          description: GitHubのユーザー名
        avatarUrl:
          type: string
          description: githubのアバター画像のURL
        characterName:
          type: string
          description: キャラクター名
        characterLevel:
          type: integer
          description: キャラクターの現在のレベル
        characterExperience:
          type: integer
          description: キャラクターの累積経験値
        characterClothes:
          type: string
          description: キャラクターの服装
        characterBackground:
          type: string
          description: キャラクターの背景
        feedCount:
          type: integer
          description: 今日の残り餌やり回数
    ProfileRequest:
      type: object
      properties:
        userId:
          type: string
          description: プロフィールを変更するユーザーのID
        characterName:
          type: string
          description: 変更するキャラクター名
      required:
        - userId
        - characterName
    GetFeedRequest:
      type: object
      properties:
        userId:
          type: string
          description: 餌を取得するユーザーのID
      required:
        - user_id
    GetFeedResponse:
      type: object
      properties:
        feed_count:
          type: integer
          description: 更新後の残り餌やり回数
    FeedRequest:
      type: object
      properties:
        userId:
          type: string
          description: 餌をあげるユーザーのID
      required:
        - userId
    FeedResponse:
      type: object
      properties:
        characterExperience:
          type: integer
          description: 更新後の経験値
        characterLevel:
          type: integer
          description: 更新後のレベル
        feedCount:
          type: integer
          description: 更新後の残り餌やり回数
    RankingResponse:
      type: object
      properties:
        rankings:
          type: array
          items:
            type: object
            properties:
              userId:
                type: string
                description: ユーザーの一意の識別子
              userName:
                type: string
                description: ユーザー名
              avatarUrl:
                type: string
                description: githubのアバター画像のURL
              characterName:
                type: string
                description: キャラクター名
              characterLevel:
                type: integer
                description: キャラクターレベル
              characterClothing:
                type: string
                description: キャラクターの服装
              characterBackground:
                type: string
                description: キャラクターの背景
          description: キャラクターレベルの高い順にソートされたユーザーのリスト
    ClothesRequest:
      type: object
      properties:
        userId:
          type: string
          description: プロフィールを変更するユーザーのID
        item:
          type: string
          enum:
            - spring
            - summer
            - autumn
            - winter
          description: 変更する服装
      required:
        - userId
        - item
    BackgroundRequest:
      type: object
      properties:
        userId:
          type: string
          description: プロフィールを変更するユーザーのID
        item:
          type: string
          enum:
            - spring
            - summer
            - autumn
            - winter
          description: 変更する背景
      required:
        - userId
        - item
